# Generated by Django 3.2.13 on 2022-06-03 00:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
        ),
    ]
